"use client";

import React, { useState } from "react";
import Image from "next/image";
import { motion, AnimatePresence } from "framer-motion";
import { Monitor, BookOpen, CreditCard, Truck, ShoppingCart } from "lucide-react";
import sellersDashBoardImg from "@/assets/images/sellersDashboard.svg";

export default function TargetSection() {
  const [activeAudience, setActiveAudience] = useState("Sellers");

  const audienceData: Record<string, { title: string; text: string; image: any }> = {
    Buyers: {
      title: "Everything You Love About Africa. Delivered to Your Door.",
      text: "Stop settling for imitations and overpriced re-sellers. Martaf connects you directly to verified African makers — so every purchase is authentic, ethically sourced, and worth every naira, dollar, or pound.",
      image: sellersDashBoardImg,
    },
    Sellers: {
      title: "Your Craft Is World-Class. Your Market Should Be Too.",
      text: "Martaf turns African makers into global brands. Stop being invisible on Instagram. Start selling to 200 million diaspora buyers and global consumers who are actively looking for what you make.",
      image: sellersDashBoardImg,
    },
    Investors: {
      title: "Scalable Growth. Tangible Impact.",
      text: "Be part of the infrastructure driving Africa's global trade revolution. Martaf provides a transparent, secure, and data-driven platform for investors to support high-growth makers and participate in the expansion of the continent's most promising export-ready brands.",
      image: sellersDashBoardImg,
    },
  };

  const journeyData: Record<string, { title: string; steps: { id: number; title: string; text: string; icon: any }[] }> = {
    Buyers: {
      title: "The Buyer Journey on Martaf",
      steps: [
        { id: 1, title: "Step 1", text: "Browse a curated marketplace of Made-in-Africa products, organized by category, origin, and maker story.", icon: <Monitor className="text-6a0dad" size={32} /> },
        { id: 2, title: "Step 2", text: "Read verified seller profiles, honest product reviews, and quality certifications before you buy.", icon: <BookOpen className="text-6a0dad" size={32} /> },
        { id: 3, title: "Step 3", text: "Pay securely in your local currency through our trusted payment system.", icon: <CreditCard className="text-6a0dad" size={32} /> },
        { id: 4, title: "Step 4", text: "Track your order from dispatch to delivery, with real-time updates and responsive customer support.", icon: <Truck className="text-6a0dad" size={32} /> },
        { id: 5, title: "Step 5", text: "Receive your product — and feel the difference of buying directly from the source.", icon: <ShoppingCart className="text-6a0dad" size={32} /> },
      ],
    },
    Sellers: {
      title: "How to Join Martaf as a Seller",
      steps: [
        { id: 1, title: "Step 1: Apply", text: "Tell us about your business, your products, and your production capacity. Applications are free.", icon: <Monitor className="text-6a0dad" size={32} /> },
        { id: 2, title: "Step 2: Get verified", text: "Our team reviews your business credentials, product samples, and quality standards.", icon: <BookOpen className="text-6a0dad" size={32} /> },
        { id: 3, title: "Step 3: Build your storefront", text: "Build your storefront. We guide you through creating your seller profile and product listings.", icon: <CreditCard className="text-6a0dad" size={32} /> },
        { id: 4, title: "Step 4: Start selling", text: "Your products go live to a global audience. Orders come in. You fulfill. Martaf handles the logistics.", icon: <Truck className="text-6a0dad" size={32} /> },
        { id: 5, title: "Step 5: Grow", text: "Use Martaf's seller analytics, buyer data, and category insights to optimize your offerings and scale your business.", icon: <ShoppingCart className="text-6a0dad" size={32} /> },
      ],
    },
    Investors: {
      title: "The Investor Journey on Martaf",
      steps: [
        { id: 1, title: "Step 1: Identify", text: "Discover high-potential African brands and artisans vetted by our quality framework.", icon: <Monitor className="text-6a0dad" size={32} /> },
        { id: 2, title: "Step 2: Analyze", text: "Access transparent growth data, market trends, and impact metrics for each category.", icon: <BookOpen className="text-6a0dad" size={32} /> },
        { id: 3, title: "Step 3: Facilitate", text: "Provide the growth capital or infrastructure support these makers need to reach global discovery.", icon: <CreditCard className="text-6a0dad" size={32} /> },
        { id: 4, title: "Step 4: Monitor", text: "Track the economic and social value generated by your investments in real-time.", icon: <Truck className="text-6a0dad" size={32} /> },
        { id: 5, title: "Step 5: Yield", text: "Benefit from the expansion of Africa's most promising export-ready brands into global markets.", icon: <ShoppingCart className="text-6a0dad" size={32} /> },
      ],
    },
  };

  return (
    <section className="my-20 md:my-40 lg:my-52 pb-24 border-b border-b-000000/12">
      <div className="px-6 md:pl-12 lg:pl-34.5">
        <div className="text-left mb-12">
          <h2 className="text-3xl md:text-5xl font-MontserratNormal text-000000 leading-[150%] mb-2">
            Who is martaf for?
          </h2>
          <p className="text-000000/68 text-base leading-[32px] font-MontserratNormal">
            Three groups. One platform.
          </p>
        </div>

        <div className="flex gap-4 mb-20 overflow-x-auto no-scrollbar">
          {["Buyers", "Sellers", "Investors"].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveAudience(tab)}
              className={`px-8 py-3 rounded-[48px] font-MontserratMedium text-c18 transition-all ${
                activeAudience === tab
                  ? "border border-6a0dad/68 text-6a0dad/68"
                  : "border border-000000/44 text-000000/44 "
              }`}
            >
              {tab}
            </button>
          ))}
        </div>

        <div className="flex flex-col md:flex-row gap-8 ">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeAudience}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 20 }}
              transition={{ duration: 0.4 }}
              className="w-full md:w-[40%]"
            >
              <h3 className="text-3xl md:text-c32 font-MontserratNormal text-000000 leading-[150%] mb-8 pt-10 ">
                {audienceData[activeAudience].title}
              </h3>
              <p className="text-6 text-000000/68 mb-8 leading-[180%]">
                {audienceData[activeAudience].text}
              </p>
            </motion.div>
          </AnimatePresence>

          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6 }}
            className="relative rounded-c16 pl-2  md:rounded-[32px] md:pl-10 lg:pl-[77px] overflow-hidden bg-white border border-[#f0f0f0] w-full md:w-[60%] h-[280px] md:h-[380px] lg:h-[430px] lg:-mr-6"
          >
            <div className="w-full h-full absolute">
              <AnimatePresence mode="wait">
                <motion.div
                  key={activeAudience}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.3 }}  
                  className="w-full h-full relative"
                >
                  <Image
                    src={audienceData[activeAudience].image}
                    alt={`${activeAudience} Dashboard Mockup`}
                    width={837}
                    height={644}
                    className="md:-mb-[67px]  -mb-[0px] w-full lg:w-[837px] h-[350px] md:h-[400px] lg:h-[486px]  "
                    priority
                  />
                </motion.div>
              </AnimatePresence>
            </div>
          </motion.div>
        </div>

        {/* Journey Section Integrated */}
        <div className="mt-16 md:mt-24 lg:mt-40 mx-auto md:px-6 ">
          <div className="text-center mb-22">
            <h2 className="text-3xl md:text-[32px] font-MontserratNormal text-000000 ">
              {journeyData[activeAudience].title}
            </h2>
          </div>

          <div className="">
            {/* First Row: 3 cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8  lg:gap-c64 mb-16  md:px-18 lg:px-[70.5px]">
              {journeyData[activeAudience].steps
                .slice(0, 3)
                .map((step, index) => (
                  <motion.div
                    key={step.id}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: index * 0.1 }}
                    viewport={{ once: true }}
                    className=" md:px-10 px-4 py-6 rounded-[32px] border border-000000/4 transition-all group min-h-[320px] flex flex-col items-start"
                  >
                    <div className="w-12 h-12 flex items-center justify-center mb-2 group-hover:scale-110 transition-transform duration-300">
                      {step.icon}
                    </div>
                    <span className="text-000000/68 font-MontserratSemiBold text-sm leading-[32px] mb-2">
                      {step.title}
                    </span>
                    <p className="text-base text-000000/68 leading-[32px] font-MontserratNormal">
                      {step.text}
                    </p>
                  </motion.div>
                ))}
            </div>

            {/* Second Row: 2 cards centered */}
            <div className="flex flex-col md:flex-row gap-8 lg:gap-c64 justify-center  md:px-18 lg:px-[70.5px]">
              {journeyData[activeAudience].steps
                .slice(3, 5)
                .map((step, index) => (
                  <motion.div
                    key={step.id}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: (index + 3) * 0.1 }}
                    viewport={{ once: true }}
                    className=" md:p-10 px-4 rounded-[32px] border border-000000/4 max-w-[362.65px] transition-all group md:w-1/2 min-h-[320px] flex flex-col items-start"
                  >
                    <div className="w-12 h-12 flex items-center justify-center mb-2 group-hover:scale-110 transition-transform duration-300">
                      {step.icon}
                    </div>
                    <span className="text-000000/68 font-MontserratSemiBold text-sm leading-[32px] mb-2">
                      {step.title}
                    </span>
                    <p className="text-base text-000000/68 leading-[32px] font-MontserratNormal">
                      {step.text}
                    </p>
                  </motion.div>
                ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
